on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.1

name: Release Gradle plugin

jobs:
  build:
    name: Publish Gradle plugin release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
          CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
          CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
          HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
        run: ./gradlew :build

      - name: Publish plugin
        env:
          HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
        run: ./gradlew :publishPlugin -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
